### ISSUE TITLE
make test fails

### ISSUE THREAD

**Issue by Guoanshisb** [uwsampa/accept#37]
Hi there,

I just installed accept and ran some tests with `make test`. However, two test cases failed with the following prompt. 

`FAIL: ACCEPT :: test_cxx.cpp (4 of 12)`
`******************* TEST 'ACCEPT :: test_cxx.cpp' FAILED ********************`
`Script:`
`--`
`../bin/enerclang++ -fsyntax-only -Xclang -verify /home/shaobo/accept/test/test_cxx.cpp`
`--`
`Exit Code: 1`
`Command Output (stderr):`
`--`
`consumer finished`
`error: 'error' diagnostics seen but not expected: `
` Line 59: 'bits/c++config.h' file not found`
`1 error generated.`
`--`

`FAIL: ACCEPT :: test_implicit.c (8 of 12)`
`******************** TEST 'ACCEPT :: test_implicit.c' FAILED ********************`
`Script:`
`--`
`../bin/enerclang -fsyntax-only -Xclang -verify /home/shaobo/accept/test/test_implicit.c`
`--`
`Exit Code: 1`
`Command Output (stderr):`
`--`
`approx void`
`Q1 const void *identifier`
`consumer finished`
`error: 'warning' diagnostics seen but not expected: `
 `Line 29: null passed to a callee which requires a non-null argument`
`1 error generated.`
`--`

I was wondering if they are expected or I messed up some stages during installation.

Thanks!

**Comment by ma3mool** [comment]
Bumping this. I get an error only on test_implicit.c

Failing Tests (1):
    ACCEPT :: test_implicit.c

  Expected Passes    : 11
  Unexpected Failures: 1
make: *** [test] Error 1

I am using ninja-1.5.3, virtualenv-12.0, and cmake-3.2.1

**Comment by sampsyo** [comment]
Thanks for the reports! No, this does not seem to be your fault, but rather platform-specific details that we haven't run into yet. Which OSes are you both running?

The `c++config.h` issue would seem to be related to differing C++ standard library implementations. I'll look into this a little more.

@ma3mool, do you see the same error message for that `test_implicit.c` failure? I'm guessing we can clean up the test to avoid this stdlib warning.

**Comment by Guoanshisb** [comment]
Thanks for your reply. The installation is on the 64bit Ubuntu 14.04.2 LTS running on a virtual machine (virtualbox).

**Comment by sampsyo** [comment]
The above commit should fix that `test_implicit.c` warning.

I'm a little confused about the C++ error you're seeing, @Guoanshisb. Is there any chance you're missing a complete standard library installation? Does `clang++` work on your system?

**Comment by Guoanshisb** [comment]
> Is there any chance you're missing a complete standard library installation?

I'm not sure. `make setup` didn't prompt any outstanding errors. Is there a way in which I can test it?
>Does `clang++` work on your system?

No, it doesn't. However, it works if I follow the instructions on this thread of stackoverflow.
http://stackoverflow.com/questions/9201521/g-4-6-issue-no-bits-cconfig-h-file-as-required-by-the-header-cstring

**Comment by sampsyo** [comment]
Awesome; thanks for investigating, @Guoanshisb! I just pushed a new command that should automatically use that workaround on your system. Can you check whether pulling this new version makes everything work?

**Comment by Guoanshisb** [comment]
Yes, everything works fine now. Thanks!

**Comment by sampsyo** [comment]
Awesome!
